services:
  dotnet-app:
    container_name: dotnet-app
    build:
      context: ./app
    image: vives/jr/webdev2:app
    ports:
      - 5001:8080
    volumes:
    - /etc/localtime:/etc/localtime:ro
    depends_on:
     - dotnet-db
    restart: unless-stopped
  dotnet-db:
    container_name: dotnet-db
    image: mariadb
    ports:
     - 3307:3306
    volumes:
     - ./db/config:/var/lib/mysql
    environment:
     - MARIADB_ROOT_PASSWORD=root
     - MARIADB_DATABASE=school
     - TZ=Europe/Brussels
    restart: unless-stopped
  dotnet-dbadmin:
    container_name: dotnet-dbadmin
    image: phpmyadmin
    ports:
     - 81:80
    environment:
     - PMA_HOST=dotnet-db
    depends_on:
     - dotnet-db
    restart: unless-stopped