services:
  dotnet-hotMeals-app:
    container_name: dotnet-hotMeals-app
    build:
      context: ./app
    image: vives/jr/webdev2:dotnet-hotMeals-app
    ports:
      - 5001:8080
    volumes:
    - /etc/localtime:/etc/localtime:ro
    environment:
     - TZ=Europe/Brussels
    depends_on:
     - dotnet-hotMeals-db
    restart: unless-stopped
  dotnet-hotMeals-db:
    container_name: dotnet-hotMeals-db
    image: mariadb
    ports:
     - 3307:3306
    volumes:
     - ./db/config:/var/lib/mysql
     - ./db/init:/docker-entrypoint-initdb.d
    environment:
     - MARIADB_ROOT_PASSWORD=root
     - MARIADB_DATABASE=school
     - TZ=Europe/Brussels
    restart: unless-stopped
  dotnet-hotMeals-dbadmin:
    container_name: dotnet-hotMeals-dbadmin
    image: phpmyadmin
    ports:
     - 81:80
    environment:
     - PMA_HOST=dotnet-hotMeals-db
    depends_on:
     - dotnet-hotMeals-db
    restart: unless-stopped
